### ISSUE TITLE
"fs" package name is likely to collide

### ISSUE THREAD

**Issue by jacobsa** [bazillion/fuse#62]
The `bazil.org/fuse/fs` package has a pretty generic name ("fs"), and it's one that's likely to collide with the name of an implementation-detail package in a tool that mounts a fuse file system -- something like `github.com/me/mytool/fs`.

In the spirit of `io/ioutil`, `net/http/httptest`, `net/http/httputil`, and so on, can I convince you to rename it to `bazil.org/fuse/fusefs`?

**Comment by tv42** [comment]
I know. I've had similar clashes. I spent time trying to come up with a better name, but couldn't come up with anything I was more happy with than just `fs`. `fuse/fusefs` was too much stutter for my tastes.

You can rename the import when necessary:

```go
import fusefs "bazil.org/fuse/fs"
```

Brilliant suggestions might still make it happen, but right now I don't think `fs` will get renamed.
