### ISSUE TITLE
Package fuse forces stat::st_nlink to be non-zero

### ISSUE THREAD

**Issue by jacobsa** [bazillion/fuse#66]
The method `Attr.attr` contains [this](https://github.com/bazillion/fuse/blob/master/fuse.go#L1118-L1120) snippet:

```Go
if out.Nlink < 1 {
  out.Nlink = 1
}
```

This effectively forbids stat(2) from ever returning nlink == 0. But that is not realistic -- it is possible for stat(2) to do that, when a file has been unlinked but some process still has it open. See for example the program below, which produces this output for the default file system on OS X:

    Nlink: 1
    Nlink: 0

The effect of this bug is that the fuse package forces fuse file systems to erroneously return nlink == 1 for unlinked files.

Program:

```Go
package main

import (
        "fmt"
        "io/ioutil"
        "os"
        "syscall"
)

func main() {
        var err error

        // Create a file.
        err = ioutil.WriteFile("bar", []byte{}, 0400)
        if err != nil {
                panic(err)
        }

        // Open it for reading.
        f, err := os.Open("bar")
        if err != nil {
                panic(err)
        }

        // Stat it.
        fi, err := f.Stat()
        if err != nil {
                panic(err)
        }

        fmt.Println("Nlink:", fi.Sys().(*syscall.Stat_t).Nlink)

        // Unlink it.
        err = os.Remove("bar")
        if err != nil {
                panic(err)
        }

        // Stat it again.
        fi, err = f.Stat()
        if err != nil {
                panic(err)
        }

        fmt.Println("Nlink:", fi.Sys().(*syscall.Stat_t).Nlink)
}
```

**Comment by tv42** [comment]
There's also https://github.com/bazillion/fuse/blob/master/fs/serve.go#L236-L238 doing a similar thing.

I agree with your diagnosis. Will remove the default once I have time to run enough tests.

**Comment by jacobsa** [comment]
If you're worried about breaking existing file systems, maybe add a mount option? I could set it for now, then later you can do your tests, and once you're finished you can remove it.

**Comment by tv42** [comment]
I want to confirm that if the default switches from 1 to 0, end-user behavior of `find` etc doesn't change in surprising way.

I'm a little worried about increasing the amount of boilerplate every FS has to carry, so I'd really love to find a clean way to let 1 remain the default value. I don't want to make it a pointer or anything like that, as database/sql etc tend to. I can't see a clean way to do that, but I'll try for a little bit longer before I just change the default.

Hope this is not too much of an inconvenience. I have to devote a full day to fuse development soon, again.

**Comment by jacobsa** [comment]
Yeah, I don't see a clean way to have a default while also allowing a zero value except for using a pointer. But that doesn't seem so bad to me...

**Comment by jacobsa** [comment]
By the way: it seems to me that in other respects all of the default behavior magic lives in the fs sub-package, and those whose use the fuse package directly are doing so because they don't want any default behavior. Certainly that is true for me. I would be completely content if you left this behavior in fs, but removed it from fuse.

**Comment by tv42** [comment]
I might make fuse/fs switch to a style where it passes in *Attr with prefilled fields, but I don't want to do that kind of an API change lightly.

**Comment by jacobsa** [comment]
Friendly ping. :-)

**Comment by jacobsa** [comment]
Another idea for evolving this in a backwards compatible way: add a `HonorNlinkZero` bool to fuse.Attr. File systems that don't want the magic behavior can set it to true. If you want to get rid of it eventually, document that not setting it to true is deprecated, and eventually after finding problematic existing users you can remove it.

**Comment by tv42** [comment]
I'm thinking of making the method be `Attr(*fuse.Attr)`.

**Comment by tv42** [comment]
I've pushed that change as branch `wip-attr`. It's an annoyingly pervasive APi change, so I'm going to hold back a moment before merging it, just in case a better idea pops up.

https://github.com/bazillion/fuse/tree/wip-attr

For the record, I didn't like the `HonorNlinkZero` because it kinda permanently complicates `Attr`, where as this approach is a one-time pain.

**Comment by jacobsa** [comment]
I guess you mean for the fs package? It looks like you fixed the issue for the parent package in 58c769aaa613a6337a22c1ef7efde3558ae04eed.

**Comment by tv42** [comment]
Yes, the low-level case was simple and is fixed.

**Comment by jacobsa** [comment]
Sounds good, thanks. (This is the case I cared about.)
