### ISSUE TITLE
Support arbitrary mount options

### ISSUE THREAD

**Issue by jacobsa** [bazillion/fuse#77]
In order to work around [osxfuse issue 199][issue], I need to set the `novncache` mount option. There are other options that would be useful to me, too.

Sending a pull request for each of these is a bit annoying, and `fuse.MountOption` is not extensible in the sense that I can't write my own, because the config struct is opaque. Can you add a function that allows me to set arbitrary mount options?
  
[issue]: https://github.com/osxfuse/osxfuse/issues/199

**Comment by tv42** [comment]
As I've explained in other pull requests, I don't want to support arbitrary (string) mount options, that leaves too much rope to shoot yourself in the foot, and the support effort of that will keep haunting me. The mount options really need to be coordinated with the filesystem implementation, and a lot of that logic lives in bazil.org/fuse/fs for your average filesystem.

I'm starting a sweep of open issues next, to deal with the actual problems.

**Comment by tv42** [comment]
BTW I just noticed you're the person behind https://github.com/jacobsa/fuse

The split between `bazil.org/fuse` and `bazil.org/fuse/fs` is still not very clean, and perhaps a lot of this programmer friendliness belongs in `fuse/fs`, while callers using `fuse` get to shoot their feet as much as they want. I don't have a concrete plan on how to evolve the APIs to suit that better; feedback from low-level users is more than welcome. The one caveat I have is this: enough people make mistakes programming to the high-level API already, it *must not* get significantly more complex or enable hard ot understand behaviors from simple configuration changes.

**Comment by jacobsa** [comment]
Yes, I agree that the base package should contain the rope to hang yourself with. (Including arbitrary mount options, in my opinion.)

Mostly I wrote that package because both fuse itself and bazil.org/fuse are severely under-documented, and I needed a place to dump my findings when trying to figure out the semantics of various things. (I am a fuse newbie, or was a few weeks ago anyway.)

**Comment by tv42** [comment]
The limit really is, `bazil.org/fuse` can only become unsafe (lots of rope) at the rate `bazil.org/fuse/fs` is able to protect the naive user from the damage. Right now, there's not much separation between those two, yet the average programmer backgrounds of people wanting these two things are very far apart. So this desire for rope ends up getting trumped by shorter-term needs -- too much rope means the current user base ends up with very few feet left, and moving on to other things in frustration. Sorry, it's a balancing act and at this point, in my opinion, this viewpoint has to loose.

I will happily add individual mount options, provided I can figure out ways to document and test them enough.

**Comment by jacobsa** [comment]
I see, thanks for explaining the conundrum. I humbly request `novncache`, which is the current outstanding issue for me.

**Comment by Artoria2e5** [comment]
I would like to revive this issue since OS X support has been retired, making it impossible to specify many useful options. If we can at least provide these as a rope interface with many warnings in big red text, those who know what they are doing can still have their stuff work.

Although some stuff can be un-roped, it is ultimately pointless for a fuse wrapper to come up with a typed interface for all the options, from the system-specific  `relatime` and `lazytime`, to the implementation-specific `big_writes` and `auto_xattr`, to the FS-specific `compression`, `posix_acl`, and `windows_names`.

**Comment by tv42** [comment]
I don't see how retiring macOS makes something useful (on non-macOS platforms) impossible.

`compression` and `windows_names`? I think you're confusing ntfs-3g's options with FUSE mount options.

Talk about specific use cases (in new issues), not vague "I might want to pass lots of options" feelings, please. If that list of use cases becomes overwhelming, *then* I might agree to adding an "anything goes" escape hatch. Right now, I'd rather have strong types & unit tests.
