### ISSUE TITLE
Install Failed

### ISSUE THREAD

**Issue by Davidx7** [bazillion/fuse#79]
On Ubuntu 14 x64 , on install I get this :: 

```
go get bazil.org/fuse
bazil.org/fuse
../go/src/bazil.org/fuse/fuse.go:330: undefined: sync.Pool
```
And stops. 
It also affects other packages importing it.

**Comment by cryptix** [comment]
Ubuntu comes with a fairly old version of golang (run `go version`). [Afaict](http://bazil.org/doc/install/), `bazil.org/fuse` needs at least go v1.2. You can either try to get a pre-build binary version or install from source. You can find more about both of these options [here](http://golang.org/doc/install).

**Comment by tv42** [comment]
In general, Ubuntu's packaged version of Go is ancient, and you should not use it for anything.

At least at one point, people active in Ubuntu said http://blog.labix.org/2013/06/15/in-flight-deb-packages-of-go was the way to get a good Go installation. I personally just install Go from source.

Bazil will most definitely keep happily using features added in the latest 1.x releases of Go, there's no point in that kind of backwards compatibility.

go 1.2 mention removed in https://github.com/bazillion/web/commit/bce2f5a1a34755cc4bb3d194a4549a70d4e77876 , thanks.
