### ISSUE TITLE
No destroy requests received on Linux

### ISSUE THREAD

**Issue by jacobsa** [bazillion/fuse#82]
I find that even with the simplest of examples, I never receive a destroy request from Conn.ReadRequest when unmounting on Linux (3.13.0-37-generic and 3.16.7-7-default). In contrast, I always receive one on OS X.

It's entirely possible this is a bug in my code, but I want to check: is this somehow expected? Do you have tests that show you do get destroy requests on Linux?

**Comment by tv42** [comment]
```go
type FSDestroyer interface {
	// Destroy is called when the file system is shutting down.
	//
	// Linux only sends this request for block device backed (fuseblk)
	// filesystems, to allow them to flush writes to disk before the
	// unmount completes.
	//
	// On normal FUSE filesystems, use Forget of the root Node to
	// do actions at unmount time.
	Destroy()
}
```

So, there's this special mode of operation called "fuseblk", and only that sees Destroy.

I've never run anything in that mode yet, personally, so I have no idea if it works right :)

Can you confirm you were in fuseblk mode, and hopefully share a small reproducing example? If not, then this is not a bug, but just how FUSE does it, and I hope the above is enough documentation (if not, please suggest improvements).

**Comment by jacobsa** [comment]
Thanks, I totally missed that because I looked in package fuse and not in package fs. No you're right, I was not using `fuseblk` mode.

Unfortunately using Forget of the root node isn't actually sufficient, because it seems like you [don't always receive](http://sourceforge.net/p/fuse/mailman/message/31995737/) the forget request on Linux.

**Comment by rohinrohin** [comment]
I had the same issue. How do I mount the filesystem in "fuseblk" mode. I was unable to find any documentation in bazil regarding this.

**Comment by tv42** [comment]
Which issue? This conversation has covered several: Destroy, Forget, doing things at unmount time.

`fuseblk` is only for actual block device backed filesystems. As far as I know, it's pretty much undocumented, anywhere. I haven't personally had any need for it, so I haven't gone reading the kernel source. If a block device backed filesystem is what you're developing, open a new issue asking for `fuseblk` support, but be prepared to put effort in it yourself.
